// Generated by https://quicktype.io

export interface CreateUserResponse {
    name: string;
    nickname: string;
    email: string;
    birthday: string;
    id_user: string;
    roles: string[];
    isBanned: boolean;
    isActive: boolean;
    profilePhoto: string;
    token: string;
}
