// Generated by https://quicktype.io

export interface LoginResponse {
    id_user: string;
    isBanned: boolean;
    isActive: boolean;
    password: string;
    email: string;
    token: string;
}
