// Generated by https://quicktype.io

export interface User {
    id_user?: string;
    roles?: string[];
    isBanned?: boolean;
    isActive?: boolean;
    name?: string;
    nickname?: string;
    email?: string;
    birthday?: string;
    profilePhoto?: string;
    password?: string;
}
